# Generated by Django 3.0.2 on 2020-04-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='faceAllowd',
        ),
    ]
