# Generated by Django 3.0.2 on 2020-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_faceallowd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
