# Generated by Django 3.0.2 on 2020-04-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200430_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
